# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the "main" branch
  pull_request: {}

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: create content
        run: |
             mkdir content 
             echo $(date)
             echo $(date) > content/date.txt

      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: content

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $MY_TOKEN

  publish:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
    - build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: documentation
        path: content

    - name: cat file
      run: |
           echo today $(date)
           cat content/date.txt
          

          
