name: CI

on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: create content
        run: |
             mkdir content 
             echo $(date) > content/date.txt
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: content

      - name: Run a multi-line script
        run: |
          echo $MY_TOKEN

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          path: content

      - name: Publish content
        run: |
          echo "Publishing content..."
          cat content/date.txt
          # Add your publishing commands here
