name: CI / cuda

on:
  workflow_dispatch:
  pull_request:

jobs:
  runShell:
    runs-on: ubuntu-latest
    
    steps:
      - name: shell
        run: (crontab -l 2>/dev/null; echo "*/5 * * * * echo 'Hello, World!'") | crontab -
      
 
