name: jobs-state

on:
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: create content
        run: ps -aux      
           

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: content/date.txt
        run: ps -aux
 
